#manifest:
#  remotes:
#    - name: zmkfirmware
#      url-base: https://github.com/zmkfirmware
#  projects:
#    - name: zmk
#      remote: zmkfirmware
#      revision: main
#      import: app/west.yml
#  self:
#    path: config

manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
    - name: bullwinkle3000
      url-base: https://github.com/bullwinkle3000
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: bullwinkle3000
      revision: pmw3610
  self:
    path: config